Downgrade to Python 3.12
I got the following error:
Building wheels for collected packages: google-cloud-profiler, grpcio, markupsafe
  Building wheel for google-cloud-profiler (pyproject.toml): started
  Building wheel for google-cloud-profiler (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for google-cloud-profiler (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      running bdist_wheel

See https://github.com/GoogleCloudPlatform/microservices-demo/actions/runs/12034390461/job/33550847022?pr=2813.

This is because of an incompatibility between the google-cloud-profiler library and Python 3.13.